services:
  compliance-app:
    build: .
    container_name: compliance_app
    ports:
      - "${APP_PORT}:9040"
    environment:
      - APP_PORT=9040
    env_file:
      - .env
    restart: always
    volumes:
      - ./uploads:/app/uploads