services:
  compliance-app:
    build: .
    container_name: compliance_app
    ports:
      - "${APP_PORT}:9040"
    environment:
      - "${APP_PORT}:9040"
      - MONGO_URI=${MONGO_URI}
      - SECRET_KEY=${SECRET_KEY}
    restart: always
    volumes:
      - ./uploads:/app/uploads